### ISSUE TITLE
ROADMAP -> PUBLISH TO CHROME STORE

### ISSUE THREAD

**Issue by FilmCoder** [FilmCoder/Slormuxify#3]
Once we get a few more kinks worked out we'll want to get this big boi hoisted up to where the large men hang.

Kinks to work out before we publish to chrome store:

- [x] #1 Dynamic Translation
- [x] #4 Engine On/Off Toggle
- [x] #6 Basic readme
- [x] #8 Engine On/Off Toggle having instant affect on webpage
- [x] Discord bot
- [x] publish dat boy

**Comment by FilmCoder** [comment]
steps here: https://developer.chrome.com/webstore/publish

**Comment by FilmCoder** [comment]
Slormuxify Chrome Plugin is now published ;) swag
